---
- hosts: all
  tasks:
  - name: Install ckan
    command: git clone https://github.com/ckan/ckan.git
    args:
      chdir: /root
    command: cp -pr .env.template .env
    command: docker-compose up -d --build
    args:
      chdir: /root/ckan/contrib/docker

